fix: add missing Newtonsoft.Json dependency (#378)
Está a acontecer um erro inesperado na produção:

```
File name: 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
Unhandled exception. System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.
at System.Reflection.RuntimeModule.GetDefinedTypes()
at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
...
at Program.<Main>$(String[] args) in /app/Program.cs:line 205
at Program.<Main>(String[] args)
System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.
File name: 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
```

Reviewed-on: https://devops-01.marinha.pt/marinha-si/Processos-Juridicos/pulls/378
Reviewed-by: ESP SIST TECN INF Matos Oliveira <matos.oliveira@marinha.pt>
Co-authored-by: m11003725 <alves.devesa@marinha.pt>
Co-committed-by: m11003725 <alves.devesa@marinha.pt>